'use client';
import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'nl';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary - add translations here
// When you update Dutch text, the English will be auto-translated via AI
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    'header.features': 'Features',
    'header.pricing': 'Pricing',
    'header.about': 'About',
    'header.login': 'Log in',
    'header.signup': 'Try 14 Days Free',
    'header.startTrial': 'Try 14 Days Free',
    'header.pdfSign': 'PDF Sign',
    
    // Hero
    'hero.badge': 'Court-admissible evidence for every delivery',
    'hero.title.line1': 'Send Files with',
    'hero.title.highlight': 'Legal Proof',
    'hero.title.line2': 'of Delivery',
    'hero.subtitle': 'TransferGuard provides registered file transfers with certified proof of delivery. Know exactly when and by whom your documents were received.',
    'hero.cta.primary': 'Start Free Trial',
    'hero.cta.secondary': 'See How It Works',
    'hero.noCreditCard': 'No credit card required',
    'hero.trialDays': '14-day free trial',
    
    // Stats
    'stats.files': 'Files Delivered',
    'stats.countries': 'Countries',
    'stats.uptime': 'Uptime',
    'stats.support': 'Support',
    
    // Features
    'features.title': 'Why Choose TransferGuard?',
    'features.subtitle': 'Legal certainty for every file transfer',
    
    // Comparison
    'comparison.title': 'The Problem We Solve',
    'comparison.theRisk': 'The Risk',
    'comparison.theSolution': 'The Solution',
    
    // Identity Verification
    'identity.title': 'Identity-Verified Delivery',
    'identity.subtitle': 'Legal-grade biometric verification',
    
    // Pricing
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.subtitle': 'Choose the plan that fits your needs',
    'pricing.professional': 'Professional',
    'pricing.legal': 'Legal',
    'pricing.perMonth': '/month',
    'pricing.startTrial': 'Start 14-Day Free Trial',
    'pricing.popular': 'Most Popular',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Everything you need to know about TransferGuard',
    
    // CTA
    'cta.title': 'Ready to Send with Legal Proof?',
    'cta.subtitle': 'Start your free trial today. No credit card required.',
    'cta.button': 'Create Free Account',
    
    // Footer
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.copyright': '© 2026 TransferGuard. A brand of PVG Technologies B.V. All Rights Reserved.',
    
    // Dashboard
    'dashboard.sentTransfers': 'Sent Transfers',
    'dashboard.pdfSign': 'Sign PDFs',
    'dashboard.certificates': 'Certificates',
    'dashboard.clientWorkspaces': 'Client Workspaces',
    'dashboard.uploadPortals': 'Upload Portals',
    'dashboard.billing': 'Billing & Credits',
    'dashboard.teamManagement': 'Team Management',
    'dashboard.contacts': 'Contacts',
    'dashboard.branding': 'Branding',
    'dashboard.profile': 'Profile',
    'dashboard.security': 'Security',
    'dashboard.newTransfer': 'New Transfer',
    'dashboard.workspace': 'Workspace',
    'dashboard.settings': 'Settings',
    'dashboard.logout': 'Log out',
    'dashboard.plan': 'Plan',
    'dashboard.loading': 'Loading...',
    'dashboard.checkingSubscription': 'Checking subscription...',
    
    // Branding Panel
    'branding.title': 'Custom Branding',
    'branding.description': 'Personalize your client-facing pages with your own brand identity',
    'branding.whereShown': 'Where is your branding displayed?',
    'branding.uploadPortal': 'Client Upload Portal',
    'branding.uploadPortalDesc': 'where clients upload files to you',
    'branding.clientWorkspaces': 'Client Workspaces',
    'branding.clientWorkspacesDesc': 'the secure environment for your recipients',
    'branding.downloadPages': 'Download Pages',
    'branding.downloadPagesDesc': 'where recipients download files',
    'branding.enableBranding': 'Enable Custom Branding',
    'branding.enableBrandingDesc': 'Show your branding on all client-facing pages',
    'branding.companyLogo': 'Company Logo',
    'branding.logoRecommendation': 'Recommended size: 200x60px, PNG or SVG with transparent background',
    'branding.uploadLogo': 'Click or drag to upload logo',
    'branding.backgroundWallpaper': 'Background Wallpaper',
    'branding.wallpaperRecommendation': 'Recommended size: 1920x1080px or larger, JPG or PNG',
    'branding.uploadWallpaper': 'Click or drag to upload wallpaper',
    'branding.brandColor': 'Brand Color',
    'branding.brandColorDesc': 'Used for buttons and accents on your branded pages',
    'branding.preview': 'Preview',
    'branding.downloadFiles': 'Download Files',
    'branding.saveSettings': 'Save Branding Settings',
    'branding.saving': 'Saving...',
    'branding.fileTooLarge': 'File size must be less than 5MB',
    'branding.onlyImages': 'Only image files are allowed',
    'branding.uploadSuccess': 'uploaded successfully',
    'branding.uploadFailed': 'Failed to upload',
    'branding.settingsSaved': 'Branding settings saved',
    'branding.saveFailed': 'Failed to save settings',
    
    // Client Workspaces
    'workspaces.title': 'Client Workspaces',
    'workspaces.subtitle': 'Secure dossier spaces for your clients with one-time identity verification',
    'workspaces.new': 'New Workspace',
    'workspaces.searchPlaceholder': 'Search by email or name...',
    'workspaces.noWorkspaces': 'No client workspaces yet',
    'workspaces.noWorkspacesDesc': 'Create a workspace for each client. After one-time identity verification, they can access all shared dossiers without re-verifying.',
    'workspaces.createFirst': 'Create First Workspace',
    'workspaces.verified': 'Verified',
    'workspaces.pendingVerification': 'Pending verification',
    'workspaces.dossiers': 'dossiers',
    'workspaces.files': 'files',
    'workspaces.new_badge': 'new',
    'workspaces.lastAccessed': 'Last accessed',
    'workspaces.created': 'Created',
    'workspaces.copyAccessLink': 'Copy access link',
    'workspaces.deleteWorkspace': 'Delete workspace',
    'workspaces.deleteConfirm': 'Are you sure you want to delete this workspace? All dossiers and files will be permanently deleted.',
    'workspaces.deleted': 'Workspace deleted',
    'workspaces.linkCopied': 'Access link copied to clipboard',
    'workspaces.createTitle': 'Create Client Workspace',
    'workspaces.createDesc': 'Create a secure workspace for your client. They will receive an access link and can verify their identity once to access all shared dossiers.',
    'workspaces.clientEmail': 'Client Email',
    'workspaces.clientName': 'Client Name (optional)',
    'workspaces.oneTimeVerification': 'One-time identity verification',
    'workspaces.verificationDesc': 'Your client will verify their identity once using biometric verification (Government ID + selfie). After that, they can access the workspace anytime without re-verifying.',
    'workspaces.cancel': 'Cancel',
    'workspaces.creating': 'Creating...',
    'workspaces.create': 'Create Workspace',
    'workspaces.created_success': 'Client workspace created!',
    'workspaces.emailRequired': 'Email is required',
    'workspaces.emailExists': 'A workspace for this email already exists',
    'workspaces.loadFailed': 'Failed to load client workspaces',
    'workspaces.createFailed': 'Failed to create workspace',
    'workspaces.deleteFailed': 'Failed to delete workspace',
    
    // Workspace Detail Tabs
    'workspaces.tab.messages': 'Messages',
    'workspaces.tab.dossiers': 'Dossiers',
    'workspaces.tab.info': 'Info',
    'workspaces.manageDossiers': 'Manage Dossiers',
    'workspaces.identityVerified': 'Identity Verified',
    'workspaces.waitingVerification': 'Waiting for Verification',
    'workspaces.clientNotVerified': 'Client has not verified yet',
    'workspaces.accessLinkLabel': 'Access link for client',
    'workspaces.sendAccessLink': 'Send Access Link',
    
    // Workspace Messages
    'messages.newMessage': 'New message',
    'messages.search': 'Search...',
    'messages.count': 'messages',
    'messages.unread': 'unread',
    'messages.loading': 'Loading messages...',
    'messages.noMessages': 'No messages',
    'messages.noMessagesDesc': 'Start a conversation with your client by sending a message.',
    'messages.noSubject': '(No subject)',
    'messages.you': 'You',
    'messages.sender': 'Sender',
    'messages.client': 'Client',
    'messages.delete': 'Delete',
    'messages.writeReply': 'Write a reply...',
    'messages.to': 'To:',
    'messages.subjectOptional': 'Subject (optional)',
    'messages.writeMessage': 'Write your message...',
    'messages.send': 'Send',
    'messages.markAsRead': 'Mark as read',
    'messages.newReceived': 'New message received',
    'messages.sent': 'Message sent',
    'messages.deleted': 'Message deleted',
    'messages.emptyError': 'Message cannot be empty',
    'messages.sendFailed': 'Could not send message',
    'messages.deleteFailed': 'Could not delete message',
    'messages.yesterday': 'Yesterday',
    'messages.attachments': 'Attachments',
    'messages.addAttachment': 'Add attachment',
    'messages.selectDossier': 'Select dossier for attachments',
    'messages.noDossiers': 'Create a dossier first to add attachments',
    'messages.maxFiles': 'Maximum 10 files per message',
    'messages.uploading': 'Uploading...',
    'messages.uploadFailed': 'Could not upload file',
    'messages.removeFile': 'Remove',
    'messages.fileAdded': 'File added',
    'messages.filesAttached': 'files attached',
    
    // Billing
    'billing.title': 'Billing & Credits',
    'billing.noTeamFound': 'No team found',
    'billing.monthly': 'Monthly',
    'billing.totalMonthlyCost': 'Total monthly cost',
    'billing.base': 'base',
    'billing.extraSeats': 'extra seats',
    'billing.activeSeats': 'Active Seats',
    'billing.seatIncluded': 'seat included',
    'billing.idVerificationCredits': 'ID Verification Credits',
    'billing.perCredit': 'per credit',
    'billing.buyCredits': 'Buy Credits',
    'billing.addSeats': 'Add Seats',
    'billing.creditsLow': 'Credits running low',
    'billing.creditsLowDesc': 'Purchase more credits to continue sending identity-verified transfers.',
    'billing.buyNow': 'Buy Now',
    'billing.priceOverview': 'Price Overview',
    'billing.item': 'Item',
    'billing.price': 'Price',
    'billing.legalBase': 'Legal Base (1 seat included)',
    'billing.total': 'Total',
    'billing.month': 'month',
    'billing.invoiceHistory': 'Invoice History',
    'billing.invoiceNumber': 'Invoice Number',
    'billing.date': 'Date',
    'billing.description': 'Description',
    'billing.amount': 'Amount',
    'billing.paid': 'Paid',
    'billing.pending': 'Pending',
    'billing.failed': 'Failed',
    'billing.buyIdCredits': 'Buy ID Verification Credits',
    'billing.creditExplainer': 'Each identity-verified transfer costs 1 credit. Credits are shared with your entire team.',
    'billing.numberOfCredits': 'Number of Credits',
    'billing.totalExclVat': 'Total (excl. VAT)',
    'billing.currentBalance': 'Current balance',
    'billing.paymentViaStripe': 'Payment will be processed via Mollie (simulated)',
    'billing.cancel': 'Cancel',
    'billing.processing': 'Processing...',
    'billing.pay': 'Pay',
    'billing.addExtraSeats': 'Add Extra Seats',
    'billing.seatExplainer': 'Add extra seats to your Legal subscription. Each seat receives 10 ID verification credits per month.',
    'billing.numberOfSeats': 'Number of Seats',
    'billing.includedPerSeat': 'Included per seat',
    'billing.creditsPerMonth': 'credits/month',
    'billing.additionalMonthlyCost': 'Additional monthly cost',
    'billing.currentSeats': 'Current seats',
    'billing.subscriptionViaStripe': 'Subscription will be updated via Mollie (simulated)',
    'billing.addMonthly': 'Add +€{amount}/month',
    'billing.noTeamDesc': 'Create a team first to manage your subscription and credits.',
    'billing.createTeam': 'Create Team',
    
    // Transfers Panel
    'transfers.title': 'Recent Transfers',
    'transfers.search': 'Search...',
    'transfers.noTransfers': 'No transfers yet',
    'transfers.noTransfersDesc': 'Send your first secure document to get started',
    'transfers.col.fileRecipient': 'File & Recipient',
    'transfers.col.reference': 'Reference',
    'transfers.col.evidence': 'Evidence Level',
    'transfers.col.status': 'Status',
    'transfers.col.actions': 'Actions',
    'transfers.btn.clone': 'Clone',
    'transfers.btn.revoke': 'Revoke',
    'transfers.btn.certificate': 'Certificate',
    'transfers.revokeTitle': 'Revoke Access',
    'transfers.revokeConfirm': 'Are you sure you want to revoke access to this transfer? The recipient will no longer be able to download the files.',
    'transfers.revokeCancel': 'Cancel',
    'transfers.revokeAction': 'Revoke Access',
    'transfers.linkCopied': 'Link copied to clipboard',
    'transfers.certificateStarted': 'Certificate download started',
    'transfers.revokeSuccess': 'Access revoked successfully',
    'transfers.revokeFailed': 'Failed to revoke access',
    'transfers.reshareSuccess': 'Document reshared successfully',
    'transfers.reshareFailed': 'Failed to reshare document',
    
    // Portals Panel
    'portals.title': 'Client Upload Portals',
    'portals.subtitle': 'Create personalized upload links for your clients',
    'portals.newPortal': 'New Portal',
    'portals.newPortalTitle': 'New Upload Portal',
    'portals.newPortalDesc': 'Create a secure upload link to share with your client.',
    'portals.name': 'Name *',
    'portals.namePlaceholder': 'e.g., Tax Documents - John Smith',
    'portals.description': 'Description (optional)',
    'portals.descPlaceholder': 'Instructions for your client...',
    'portals.expiryDate': 'Expiry Date (optional)',
    'portals.idVerification': 'ID Verification',
    'portals.idVerifyDesc': 'Clients must verify their identity with biometric ID before uploading (legally binding).',
    'portals.idVerifyUpgradeDesc': 'Require biometric identity verification before clients can upload documents.',
    'portals.activeImmediately': 'Active immediately',
    'portals.active': 'Active',
    'portals.inactive': 'Inactive',
    'portals.cancel': 'Cancel',
    'portals.createPortal': 'Create Portal',
    'portals.encrypted': 'End-to-end Encrypted',
    'portals.encryptedDesc': 'All uploads via your portals are secured with end-to-end encryption and appear automatically in your dashboard with your own branding.',
    'portals.noPortals': 'No upload portals yet',
    'portals.noPortalsDesc': 'Create a portal to let clients upload documents securely.',
    'portals.createFirst': 'Create First Portal',
    'portals.copyLink': 'Link',
    'portals.submissions': 'Submissions',
    'portals.viewPortal': 'View Portal',
    'portals.edit': 'Edit',
    'portals.delete': 'Delete',
    'portals.editTitle': 'Edit Portal',
    'portals.saveChanges': 'Save Changes',
    'portals.created': 'Created',
    'portals.expires': 'Expires',
    'portals.upgrade': 'Upgrade',
    'portals.linkCopied': 'Link copied!',
    'portals.portalCreated': 'Upload portal created!',
    'portals.portalUpdated': 'Portal updated!',
    'portals.portalDeleted': 'Portal deleted',
    'portals.loadFailed': 'Could not load portals',
    'portals.createFailed': 'Could not create portal',
    'portals.updateFailed': 'Could not update portal',
    'portals.deleteFailed': 'Could not delete portal',
    'portals.deleteConfirm': 'Are you sure you want to delete',
    'portals.nameRequired': 'Please enter a name',
    'portals.phoneRequired': 'Phone number is required for SMS verification',
    'portals.submissionsTitle': 'Submissions',
    'portals.submissionsDesc': 'View all documents submitted via this portal.',
    'portals.noSubmissions': 'No submissions yet',
    'portals.expired': 'Expired',
    'portals.files': 'files',
    'portals.file': 'file',
    
    // Certificates Panel
    'certificates.title': 'Delivery Certificates',
    'certificates.description': 'Download legal proof of delivery for each successful download. These certificates include timestamp, IP address, and recipient verification.',
    'certificates.noCertificates': 'No certificates yet',
    'certificates.noCertificatesDesc': 'Certificates are generated when recipients download your documents',
    'certificates.deliveredTo': 'Successfully delivered to',
    'certificates.download': 'Certificate',
    'certificates.downloaded': 'Certificate downloaded',
    
    // Security Panel
    'security.title': 'Security Settings',
    'security.senderVerification': 'Sender Identity Verification',
    'security.twoFactor': 'Two-Factor Authentication',
    'security.changePassword': 'Change Password',
    'security.changePasswordDesc': 'Update your password to keep your account secure. We recommend using a strong, unique password.',
    'security.newPassword': 'New Password',
    'security.newPasswordPlaceholder': 'Enter new password',
    'security.minChars': 'Minimum 8 characters',
    'security.confirmPassword': 'Confirm New Password',
    'security.confirmPasswordPlaceholder': 'Confirm new password',
    'security.changingPassword': 'Changing...',
    'security.changePasswordBtn': 'Change Password',
    'security.passwordChanged': 'Password changed successfully',
    'security.passwordsRequired': 'Please fill in all password fields',
    'security.passwordTooShort': 'Password must be at least 8 characters',
    'security.passwordsMismatch': 'Passwords do not match',
    'security.passwordFailed': 'Failed to change password',
    'security.loginHistory': 'Login History',
    'security.loginHistoryDesc': 'Recent sign-in activity for your account.',
    'security.loginHistorySoon': 'Login history will be available soon.',
    'security.loginHistorySoonDesc': "We're working on tracking login activity for your security.",
    'security.unknownDevice': 'Unknown device',
    'security.unknownIP': 'Unknown IP',
    
    // MFA Settings
    'mfa.title': 'Two-Factor Authentication',
    'mfa.enabledDesc': 'Your account is protected with an authenticator app.',
    'mfa.disabledDesc': 'Add an extra layer of security to your account by requiring a code from your authenticator app when signing in.',
    'mfa.disable': 'Disable 2FA',
    'mfa.enable': 'Enable 2FA',
    'mfa.disableTitle': 'Disable Two-Factor Authentication?',
    'mfa.disableDesc': 'This will remove the extra security layer from your account. You can enable it again at any time.',
    'mfa.cancel': 'Cancel',
    'mfa.disabling': 'Disabling...',
    'mfa.enableTitle': 'Enable Two-Factor Authentication',
    'mfa.enableDesc': 'Set up an authenticator app to secure your account',
    'mfa.enabled': 'Two-factor authentication enabled!',
    'mfa.disabled': 'Two-factor authentication disabled',
    'mfa.disableFailed': 'Failed to disable 2FA',
    
    // Profile Panel
    'profile.title': 'My Profile',
    'profile.save': 'Save',
    'profile.saving': 'Saving...',
    'profile.changePhoto': 'Change photo',
    'profile.uploadPhoto': 'Upload photo',
    'profile.removePhoto': 'Remove',
    'profile.personalInfo': 'Personal Information',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.companyInfo': 'Company Information',
    'profile.companyName': 'Company Name',
    'profile.phone': 'Phone',
    'profile.addressInfo': 'Address Information',
    'profile.address': 'Address',
    'profile.postalCode': 'Postal Code',
    'profile.city': 'City',
    'profile.country': 'Country',
    'profile.loading': 'Loading...',
    'profile.notFound': 'Profile not found',
    'profile.loadError': 'Error loading profile',
    'profile.saveError': 'Error saving',
    'profile.saved': 'Profile saved',
    'profile.photoUpdated': 'Profile photo updated!',
    'profile.photoRemoved': 'Profile photo removed',
    'profile.photoUploadFailed': 'Failed to upload photo',
    'profile.photoRemoveFailed': 'Failed to remove photo',
    'profile.invalidFileType': 'Please upload a JPG, PNG, WebP, or GIF image',
    'profile.fileTooLarge': 'Image must be smaller than 5MB',
    
    // Contacts Panel
    'contacts.title': 'Contacts',
    'contacts.newGroup': 'New Group',
    'contacts.addContact': 'Add Contact',
    'contacts.noContacts': 'No contacts yet',
    'contacts.noContactsDesc': 'Add contacts to quickly share files',
    'contacts.otherContacts': 'Other Contacts',
    'contacts.noContactsInGroup': 'No contacts in this group',
    'contacts.deleteGroupConfirm': 'Are you sure you want to delete this group?',
    'contacts.groupDeleted': 'Group deleted',
    'contacts.contactDeleted': 'Contact deleted',
    'contacts.deleteError': 'Error deleting',
    'contacts.newGroupTitle': 'New Group',
    'contacts.groupName': 'Group Name',
    'contacts.groupNamePlaceholder': 'e.g. Colleagues',
    'contacts.groupDescription': 'Description (optional)',
    'contacts.groupDescPlaceholder': 'Short description',
    'contacts.cancel': 'Cancel',
    'contacts.create': 'Create',
    'contacts.groupCreated': 'Group created',
    'contacts.groupCreateError': 'Error creating group',
    'contacts.addContactTitle': 'Add Contact',
    'contacts.email': 'Email *',
    'contacts.emailPlaceholder': 'email@example.com',
    'contacts.name': 'Name (optional)',
    'contacts.namePlaceholder': 'John Doe',
    'contacts.add': 'Add',
    'contacts.contactAdded': 'Contact added',
    'contacts.contactAddError': 'Error adding contact',
    'contacts.contactsLoadError': 'Error loading contacts',
    'contacts.groupsLoadError': 'Error loading groups',
    'contacts.delete': 'Delete',
    
    // About page
    'about.label': 'About Us',
    'about.title.line1': 'Secure Registered',
    'about.title.line2': 'Document Delivery',
    'about.subtitle': 'TransferGuard is the trusted platform for sending documents with legally binding proof of delivery. We combine enterprise-grade security with EU-compliant infrastructure.',
    'about.badge.gdpr': 'Compliant',
    'about.badge.iso': 'Certified',
    'about.badge.aes': 'Encryption',
    'about.why.title': 'Why TransferGuard?',
    'about.why.p1': "Traditional email and file sharing services can't prove that your documents were actually received. When it matters legally — contracts, legal notices, compliance deadlines — you need verifiable proof of delivery.",
    'about.why.p2': "That's exactly what TransferGuard provides.",
    'about.why.p3': 'We combine secure file transfer with legally binding delivery certificates. Every transfer is tracked, timestamped, and documented. For our Legal plan, we provide biometric identity verification combined with cryptographic proof, creating strong circumstantial evidence that holds up in civil proceedings.',
    'about.why.p4': 'Our infrastructure runs exclusively on ISO 27001 certified European servers. Your data never leaves the EU, ensuring full GDPR compliance and protection from foreign data access laws.',
    'about.why.p5': "Whether you're a law firm sending case documents, a notary delivering contracts, or a business sharing sensitive files — TransferGuard gives you the security and proof you need.",
    'about.values.label': 'Values',
    'about.values.title.part1': 'Built on ',
    'about.values.title.trust': 'Trust',
    'about.values.title.security': 'Security',
    'about.values.title.legal': 'Legal Certainty',
    'about.values.subtitle.bold': 'Our Promise to You.',
    'about.values.subtitle': ' These principles guide every decision we make.',
    'about.value.proof.title': 'Proof of Delivery',
    'about.value.proof.desc': 'We provide legally binding proof that your documents were delivered and received. Essential for contracts, legal notices, and compliance requirements.',
    'about.value.secure.title': 'Secure by Default',
    'about.value.secure.desc': 'End-to-end encryption ensures your files are protected from upload to download. Only you and your intended recipient can access the content.',
    'about.value.eu.title': 'EU Infrastructure',
    'about.value.eu.desc': 'All data is processed and stored exclusively within ISO 27001 certified EU data centers, protected by GDPR and European privacy regulations.',
    'about.value.professionals.title': 'Built for Professionals',
    'about.value.professionals.desc': 'Designed for law firms, notaries, healthcare providers, and businesses that need verifiable proof of document delivery.',
    'about.value.privacy.title': 'Privacy First',
    'about.value.privacy.desc': 'Your files are never scanned, analyzed, or used for any purpose other than secure delivery. We respect your data privacy.',
    'about.value.independent.title': 'Independent & Trusted',
    'about.value.independent.desc': 'We are a fully independent European company. No big tech affiliations, no data mining, no compromises on your security.',
    'about.promise.title': 'Our Data Promise',
    'about.promise.subtitle': 'Your trust is our most valuable asset. Here is our commitment to protecting your privacy.',
    'about.promise.nosell.title': 'We will never sell your data',
    'about.promise.nosell.highlight': 'never sell',
    'about.promise.nosell.desc': 'Your files and metadata are not for sale. Not now, not ever.',
    'about.promise.noai.title': 'We will never train AI on your files',
    'about.promise.noai.highlight': 'never train AI',
    'about.promise.noai.desc': 'Your documents, photos, and files are yours alone.',
    'about.promise.nocloudact.title': 'No US Cloud Act Risk',
    'about.promise.nocloudact.highlight': 'No US Cloud Act',
    'about.promise.nocloudact.desc': 'Unlike US providers (Dropbox, WeTransfer), we are not subject to the US Cloud Act. Your data remains strictly under European law.',
    'about.promise.transparent.title': 'We will always be transparent',
    'about.promise.transparent.highlight': 'always be transparent',
    'about.promise.transparent.desc': "If our policies change, you'll be the first to know.",
    'about.cta.title': 'Ready to get started?',
    'about.cta.subtitle': 'Start your 14-day free trial today. No credit card needed.',
    'about.cta.primary': 'Try 14 Days Free',
    'about.cta.secondary': 'View Pricing',
    
    // Contact page
    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions about TransferGuard? Need help with your account? We are here to help.',
    'contact.formTitle': 'Send us a message',
    'contact.name': 'Name *',
    'contact.namePlaceholder': 'Your name',
    'contact.email': 'Email *',
    'contact.topic': 'Topic *',
    'contact.topicPlaceholder': 'Select a topic',
    'contact.topicSales': 'Sales',
    'contact.topicSupport': 'Technical Support',
    'contact.topicBilling': 'Billing',
    'contact.topicPartnership': 'Partnership',
    'contact.topicOther': 'Other',
    'contact.subject': 'Subject *',
    'contact.subjectPlaceholder': 'How can we help?',
    'contact.message': 'Message *',
    'contact.messagePlaceholder': 'Tell us more about your question or issue...',
    'contact.send': 'Send Message',
    'contact.success': "Thank you for your message! We'll get back to you within 24 hours.",
    'contact.responseTime': 'Response Time',
    'contact.responseTimeDesc': 'We typically respond within',
    'contact.responseTimeHighlight': '24 hours',
    'contact.responseTimeSuffix': 'during business days.',
    'contact.businessHours': 'Monday - Friday, 9:00 AM - 6:00 PM CET',
    'contact.location': 'Location',
    'contact.locationDesc': '🇪🇺 Based in the European Union',
  },
  nl: {
    // Header
    'header.features': 'Functies',
    'header.pricing': 'Prijzen',
    'header.about': 'Over ons',
    'header.login': 'Inloggen',
    'header.signup': 'Probeer 14 dagen gratis',
    'header.startTrial': 'Probeer 14 dagen gratis',
    'header.pdfSign': 'PDF Ondertekenen',
    
    // Hero
    'hero.badge': 'Juridisch bewijs voor elke verzending',
    'hero.title.line1': 'Verstuur bestanden met',
    'hero.title.highlight': 'juridisch bewijs',
    'hero.title.line2': 'van ontvangst',
    'hero.subtitle': 'TransferGuard biedt geregistreerde bestandsoverdrachten met gecertificeerd bewijs van ontvangst. U weet precies wanneer en door wie uw documenten zijn ontvangen.',
    'hero.cta.primary': 'Start gratis proefperiode',
    'hero.cta.secondary': 'Bekijk hoe het werkt',
    'hero.noCreditCard': 'Geen creditcard nodig',
    'hero.trialDays': '14 dagen gratis proberen',
    
    // Stats
    'stats.files': 'Verzonden bestanden',
    'stats.countries': 'Landen',
    'stats.uptime': 'Uptime',
    'stats.support': 'Ondersteuning',
    
    // Features
    'features.title': 'Waarom TransferGuard?',
    'features.subtitle': 'Juridische zekerheid voor elke bestandsoverdracht',
    
    // Comparison
    'comparison.title': 'Het probleem dat wij oplossen',
    'comparison.theRisk': 'Het risico',
    'comparison.theSolution': 'De oplossing',
    
    // Identity Verification
    'identity.title': 'Identiteitsgeverifieerde levering',
    'identity.subtitle': 'Biometrische verificatie op juridisch niveau',
    
    // Pricing
    'pricing.title': 'Eenvoudige, transparante prijzen',
    'pricing.subtitle': 'Kies het abonnement dat bij u past',
    'pricing.professional': 'Professional',
    'pricing.legal': 'Legal',
    'pricing.perMonth': '/maand',
    'pricing.startTrial': 'Start 14 dagen gratis proefperiode',
    'pricing.popular': 'Meest populair',
    
    // FAQ
    'faq.title': 'Veelgestelde vragen',
    'faq.subtitle': 'Alles wat u moet weten over TransferGuard',
    
    // CTA
    'cta.title': 'Klaar om te versturen met juridisch bewijs?',
    'cta.subtitle': 'Start vandaag nog uw gratis proefperiode. Geen creditcard nodig.',
    'cta.button': 'Gratis account aanmaken',
    
    // Footer
    'footer.product': 'Product',
    'footer.company': 'Bedrijf',
    'footer.legal': 'Juridisch',
    'footer.copyright': '© 2026 TransferGuard. Een merk van PVG Technologies B.V. Alle rechten voorbehouden.',
    
    // Dashboard
    'dashboard.sentTransfers': 'Verzonden transfers',
    'dashboard.pdfSign': 'PDF ondertekenen',
    'dashboard.certificates': 'Certificaten',
    'dashboard.clientWorkspaces': 'Klantwerkruimtes',
    'dashboard.uploadPortals': 'Uploadportalen',
    'dashboard.billing': 'Facturatie & tegoed',
    'dashboard.teamManagement': 'Teambeheer',
    'dashboard.contacts': 'Contacten',
    'dashboard.branding': 'Huisstijl',
    'dashboard.profile': 'Profiel',
    'dashboard.security': 'Beveiliging',
    'dashboard.newTransfer': 'Nieuwe transfer',
    'dashboard.workspace': 'Werkruimte',
    'dashboard.settings': 'Instellingen',
    'dashboard.logout': 'Uitloggen',
    'dashboard.plan': 'Abonnement',
    'dashboard.loading': 'Laden...',
    'dashboard.checkingSubscription': 'Abonnement controleren...',
    
    // Branding Panel
    'branding.title': 'Eigen Huisstijl',
    'branding.description': 'Personaliseer uw klantgerichte pagina\'s met uw eigen huisstijl',
    'branding.whereShown': 'Waar wordt uw huisstijl getoond?',
    'branding.uploadPortal': 'Client Upload Portaal',
    'branding.uploadPortalDesc': 'waar klanten bestanden naar u uploaden',
    'branding.clientWorkspaces': 'Klantwerkruimtes',
    'branding.clientWorkspacesDesc': 'de beveiligde omgeving voor uw ontvangers',
    'branding.downloadPages': 'Downloadpagina\'s',
    'branding.downloadPagesDesc': 'waar ontvangers bestanden downloaden',
    'branding.enableBranding': 'Activeer Eigen Huisstijl',
    'branding.enableBrandingDesc': 'Toon uw huisstijl op alle klantgerichte pagina\'s',
    'branding.companyLogo': 'Bedrijfslogo',
    'branding.logoRecommendation': 'Aanbevolen formaat: 200x60px, PNG of SVG met transparante achtergrond',
    'branding.uploadLogo': 'Klik of sleep om logo te uploaden',
    'branding.backgroundWallpaper': 'Achtergrondafbeelding',
    'branding.wallpaperRecommendation': 'Aanbevolen formaat: 1920x1080px of groter, JPG of PNG',
    'branding.uploadWallpaper': 'Klik of sleep om achtergrond te uploaden',
    'branding.brandColor': 'Merkkleur',
    'branding.brandColorDesc': 'Wordt gebruikt voor knoppen en accenten op uw gepersonaliseerde pagina\'s',
    'branding.preview': 'Voorbeeld',
    'branding.downloadFiles': 'Bestanden downloaden',
    'branding.saveSettings': 'Huisstijl opslaan',
    'branding.saving': 'Opslaan...',
    'branding.fileTooLarge': 'Bestand moet kleiner zijn dan 5MB',
    'branding.onlyImages': 'Alleen afbeeldingen zijn toegestaan',
    'branding.uploadSuccess': 'succesvol geüpload',
    'branding.uploadFailed': 'Uploaden mislukt',
    'branding.settingsSaved': 'Huisstijl instellingen opgeslagen',
    'branding.saveFailed': 'Opslaan mislukt',
    
    // Client Workspaces
    'workspaces.title': 'Klantwerkruimtes',
    'workspaces.subtitle': 'Beveiligde dossierruimtes voor uw klanten met eenmalige identiteitsverificatie',
    'workspaces.new': 'Nieuwe werkruimte',
    'workspaces.searchPlaceholder': 'Zoeken op e-mail of naam...',
    'workspaces.noWorkspaces': 'Nog geen klantwerkruimtes',
    'workspaces.noWorkspacesDesc': 'Maak een werkruimte voor elke klant. Na eenmalige identiteitsverificatie hebben zij toegang tot alle gedeelde dossiers zonder opnieuw te verifiëren.',
    'workspaces.createFirst': 'Eerste werkruimte aanmaken',
    'workspaces.verified': 'Geverifieerd',
    'workspaces.pendingVerification': 'Wacht op verificatie',
    'workspaces.dossiers': 'dossiers',
    'workspaces.files': 'bestanden',
    'workspaces.new_badge': 'nieuw',
    'workspaces.lastAccessed': 'Laatst bezocht',
    'workspaces.created': 'Aangemaakt',
    'workspaces.copyAccessLink': 'Kopieer toegangslink',
    'workspaces.deleteWorkspace': 'Werkruimte verwijderen',
    'workspaces.deleteConfirm': 'Weet u zeker dat u deze werkruimte wilt verwijderen? Alle dossiers en bestanden worden permanent verwijderd.',
    'workspaces.deleted': 'Werkruimte verwijderd',
    'workspaces.linkCopied': 'Toegangslink gekopieerd naar klembord',
    'workspaces.createTitle': 'Klantwerkruimte aanmaken',
    'workspaces.createDesc': 'Maak een beveiligde werkruimte voor uw klant. Zij ontvangen een toegangslink en kunnen hun identiteit eenmalig verifiëren om toegang te krijgen tot alle gedeelde dossiers.',
    'workspaces.clientEmail': 'E-mail klant',
    'workspaces.clientName': 'Naam klant (optioneel)',
    'workspaces.oneTimeVerification': 'Eenmalige identiteitsverificatie',
    'workspaces.verificationDesc': 'Uw klant verifieert hun identiteit eenmalig via biometrische verificatie (ID-document + selfie). Daarna kunnen zij de werkruimte op elk moment bezoeken zonder opnieuw te verifiëren.',
    'workspaces.cancel': 'Annuleren',
    'workspaces.creating': 'Aanmaken...',
    'workspaces.create': 'Werkruimte aanmaken',
    'workspaces.created_success': 'Klantwerkruimte aangemaakt!',
    'workspaces.emailRequired': 'E-mail is verplicht',
    'workspaces.emailExists': 'Er bestaat al een werkruimte voor dit e-mailadres',
    'workspaces.loadFailed': 'Kon klantwerkruimtes niet laden',
    'workspaces.createFailed': 'Kon werkruimte niet aanmaken',
    'workspaces.deleteFailed': 'Kon werkruimte niet verwijderen',
    
    // Workspace Detail Tabs
    'workspaces.tab.messages': 'Berichten',
    'workspaces.tab.dossiers': 'Dossiers',
    'workspaces.tab.info': 'Info',
    'workspaces.manageDossiers': 'Beheer Dossiers',
    'workspaces.identityVerified': 'Identiteit Geverifieerd',
    'workspaces.waitingVerification': 'Wacht op Verificatie',
    'workspaces.clientNotVerified': 'Klant heeft nog niet geverifieerd',
    'workspaces.accessLinkLabel': 'Toegangslink voor klant',
    'workspaces.sendAccessLink': 'Stuur Toegangslink',
    
    // Workspace Messages
    'messages.newMessage': 'Nieuw bericht',
    'messages.search': 'Zoeken...',
    'messages.count': 'berichten',
    'messages.unread': 'ongelezen',
    'messages.loading': 'Berichten laden...',
    'messages.noMessages': 'Geen berichten',
    'messages.noMessagesDesc': 'Begin een gesprek met uw klant door een bericht te sturen.',
    'messages.noSubject': '(Geen onderwerp)',
    'messages.you': 'Jij',
    'messages.sender': 'Verzender',
    'messages.client': 'Klant',
    'messages.delete': 'Verwijderen',
    'messages.writeReply': 'Schrijf een antwoord...',
    'messages.to': 'Aan:',
    'messages.subjectOptional': 'Onderwerp (optioneel)',
    'messages.writeMessage': 'Schrijf je bericht...',
    'messages.send': 'Verzenden',
    'messages.markAsRead': 'Markeer als gelezen',
    'messages.newReceived': 'Nieuw bericht ontvangen',
    'messages.sent': 'Bericht verzonden',
    'messages.deleted': 'Bericht verwijderd',
    'messages.emptyError': 'Bericht mag niet leeg zijn',
    'messages.sendFailed': 'Kon bericht niet verzenden',
    'messages.deleteFailed': 'Kon bericht niet verwijderen',
    'messages.yesterday': 'Gisteren',
    'messages.attachments': 'Bijlagen',
    'messages.addAttachment': 'Bijlage toevoegen',
    'messages.selectDossier': 'Selecteer dossier voor bijlagen',
    'messages.noDossiers': 'Maak eerst een dossier aan om bijlagen toe te voegen',
    'messages.maxFiles': 'Maximaal 10 bestanden per bericht',
    'messages.uploading': 'Uploaden...',
    'messages.uploadFailed': 'Kon bestand niet uploaden',
    'messages.removeFile': 'Verwijderen',
    'messages.fileAdded': 'Bestand toegevoegd',
    'messages.filesAttached': 'bestanden bijgevoegd',
    
    // Billing
    'billing.title': 'Facturatie & Credits',
    'billing.noTeamFound': 'Geen team gevonden',
    'billing.monthly': 'Maandelijks',
    'billing.totalMonthlyCost': 'Totale maandkosten',
    'billing.base': 'basis',
    'billing.extraSeats': 'extra seats',
    'billing.activeSeats': 'Actieve Seats',
    'billing.seatIncluded': 'seat inbegrepen',
    'billing.idVerificationCredits': 'ID Verification Credits',
    'billing.perCredit': 'per credit',
    'billing.buyCredits': 'Koop Credits',
    'billing.addSeats': 'Voeg Seats Toe',
    'billing.creditsLow': 'Credits bijna op',
    'billing.creditsLowDesc': 'Koop extra credits om identity-verified transfers te blijven versturen.',
    'billing.buyNow': 'Koop Nu',
    'billing.priceOverview': 'Prijsoverzicht',
    'billing.item': 'Onderdeel',
    'billing.price': 'Prijs',
    'billing.legalBase': 'Legal Basis (1 seat inbegrepen)',
    'billing.total': 'Totaal',
    'billing.month': 'maand',
    'billing.invoiceHistory': 'Factuurgeschiedenis',
    'billing.invoiceNumber': 'Factuurnummer',
    'billing.date': 'Datum',
    'billing.description': 'Omschrijving',
    'billing.amount': 'Bedrag',
    'billing.paid': 'Betaald',
    'billing.pending': 'In behandeling',
    'billing.failed': 'Mislukt',
    'billing.buyIdCredits': 'ID Verification Credits Kopen',
    'billing.creditExplainer': 'Elke identity-verified transfer kost 1 credit. Credits worden gedeeld met je hele team.',
    'billing.numberOfCredits': 'Aantal Credits',
    'billing.totalExclVat': 'Totaal (excl. BTW)',
    'billing.currentBalance': 'Huidig saldo',
    'billing.paymentViaStripe': 'Betaling wordt verwerkt via Mollie (gesimuleerd)',
    'billing.cancel': 'Annuleren',
    'billing.processing': 'Verwerken...',
    'billing.pay': 'Betaal',
    'billing.addExtraSeats': 'Extra Seats Toevoegen',
    'billing.seatExplainer': 'Voeg extra seats toe aan je Verified Identity abonnement. Elk seat krijgt 10 ID verification credits per maand.',
    'billing.numberOfSeats': 'Aantal Seats',
    'billing.includedPerSeat': 'Inclusief per seat',
    'billing.creditsPerMonth': 'credits/maand',
    'billing.additionalMonthlyCost': 'Extra maandkosten',
    'billing.currentSeats': 'Huidige seats',
    'billing.subscriptionViaStripe': 'Abonnement wordt bijgewerkt via Mollie (gesimuleerd)',
    'billing.addMonthly': '+€{amount}/maand toevoegen',
    'billing.noTeamDesc': 'Maak eerst een team aan om je abonnement en credits te beheren.',
    'billing.createTeam': 'Team Aanmaken',
    
    // About page
    'about.label': 'Over ons',
    'about.title.line1': 'Veilige Geregistreerde',
    'about.title.line2': 'Documentlevering',
    'about.subtitle': 'TransferGuard is het vertrouwde platform voor het versturen van documenten met juridisch bindend bewijs van ontvangst. Wij combineren enterprise-grade beveiliging met EU-conforme infrastructuur.',
    'about.badge.gdpr': 'Conform',
    'about.badge.iso': 'Gecertificeerd',
    'about.badge.aes': 'Encryptie',
    'about.why.title': 'Waarom TransferGuard?',
    'about.why.p1': 'Traditionele e-mail- en bestandsuitwisselingsdiensten kunnen niet bewijzen dat uw documenten daadwerkelijk zijn ontvangen. Wanneer het juridisch van belang is — contracten, juridische kennisgevingen, nalevingsdeadlines — heeft u verifieerbaar bewijs van ontvangst nodig.',
    'about.why.p2': 'Dat is precies wat TransferGuard biedt.',
    'about.why.p3': 'Wij combineren veilige bestandsoverdracht met juridisch bindende leveringscertificaten. Elke overdracht wordt gevolgd, voorzien van een tijdstempel en gedocumenteerd. Voor ons Verified Identity abonnement bieden wij biometrische identiteitsverificatie gecombineerd met cryptografisch bewijs, waardoor sterk indirect bewijs ontstaat dat standhoudt in civiele procedures.',
    'about.why.p4': 'Onze infrastructuur draait uitsluitend op ISO 27001-gecertificeerde Europese servers. Uw gegevens verlaten nooit de EU, wat volledige GDPR-conformiteit en bescherming tegen buitenlandse wetgeving voor gegevenstoegang garandeert.',
    'about.why.p5': 'Of u nu een advocatenkantoor bent dat dossierstukken verstuurt, een notaris die contracten levert, of een bedrijf dat gevoelige bestanden deelt — TransferGuard geeft u de beveiliging en het bewijs dat u nodig heeft.',
    'about.values.label': 'Waarden',
    'about.values.title.part1': 'Gebouwd op ',
    'about.values.title.trust': 'Vertrouwen',
    'about.values.title.security': 'Veiligheid',
    'about.values.title.legal': 'Juridische Zekerheid',
    'about.values.subtitle.bold': 'Onze belofte aan u.',
    'about.values.subtitle': ' Deze principes sturen elke beslissing die wij nemen.',
    'about.value.proof.title': 'Bewijs van Ontvangst',
    'about.value.proof.desc': 'Wij leveren juridisch bindend bewijs dat uw documenten zijn afgeleverd en ontvangen. Essentieel voor contracten, juridische kennisgevingen en nalevingsvereisten.',
    'about.value.secure.title': 'Standaard Beveiligd',
    'about.value.secure.desc': 'End-to-end encryptie zorgt ervoor dat uw bestanden beschermd zijn van upload tot download. Alleen u en uw beoogde ontvanger hebben toegang tot de inhoud.',
    'about.value.eu.title': 'EU-infrastructuur',
    'about.value.eu.desc': 'Alle gegevens worden uitsluitend verwerkt en opgeslagen in ISO 27001-gecertificeerde EU-datacenters, beschermd door GDPR en Europese privacyregelgeving.',
    'about.value.professionals.title': 'Gebouwd voor Professionals',
    'about.value.professionals.desc': 'Ontworpen voor advocatenkantoren, notarissen, zorgverleners en bedrijven die verifieerbaar bewijs van documentlevering nodig hebben.',
    'about.value.privacy.title': 'Privacy Eerst',
    'about.value.privacy.desc': 'Uw bestanden worden nooit gescand, geanalyseerd of gebruikt voor enig ander doel dan veilige levering. Wij respecteren uw gegevensprivacy.',
    'about.value.independent.title': 'Onafhankelijk & Betrouwbaar',
    'about.value.independent.desc': 'Wij zijn een volledig onafhankelijk Europees bedrijf. Geen big tech-banden, geen datamining, geen compromissen op uw beveiliging.',
    'about.promise.title': 'Onze Data Belofte',
    'about.promise.subtitle': 'Uw vertrouwen is ons meest waardevolle bezit. Dit is onze toezegging om uw privacy te beschermen.',
    'about.promise.nosell.title': 'Wij zullen nooit uw gegevens verkopen',
    'about.promise.nosell.highlight': 'nooit uw gegevens verkopen',
    'about.promise.nosell.desc': 'Uw bestanden en metadata zijn niet te koop. Niet nu, niet ooit.',
    'about.promise.noai.title': 'Wij zullen nooit AI trainen op uw bestanden',
    'about.promise.noai.highlight': 'nooit AI trainen',
    'about.promise.noai.desc': 'Uw documenten, foto\'s en bestanden zijn uitsluitend van u.',
    'about.promise.nocloudact.title': 'Geen US Cloud Act Risico',
    'about.promise.nocloudact.highlight': 'Geen US Cloud Act',
    'about.promise.nocloudact.desc': 'Anders dan Amerikaanse aanbieders (Dropbox, WeTransfer) vallen wij niet onder de US Cloud Act. Uw gegevens blijven strikt onder Europese wetgeving.',
    'about.promise.transparent.title': 'Wij zullen altijd transparant zijn',
    'about.promise.transparent.highlight': 'altijd transparant',
    'about.promise.transparent.desc': 'Als ons beleid verandert, bent u de eerste die het weet.',
    'about.cta.title': 'Klaar om te beginnen?',
    'about.cta.subtitle': 'Start vandaag uw gratis proefperiode van 14 dagen. Geen creditcard nodig.',
    'about.cta.primary': 'Probeer 14 dagen gratis',
    'about.cta.secondary': 'Bekijk Prijzen',
    
    // Contact page
    'contact.title': 'Neem Contact Op',
    'contact.subtitle': 'Heeft u vragen over TransferGuard? Hulp nodig met uw account? Wij helpen u graag.',
    'contact.formTitle': 'Stuur ons een bericht',
    'contact.name': 'Naam *',
    'contact.namePlaceholder': 'Uw naam',
    'contact.email': 'E-mail *',
    'contact.topic': 'Onderwerp *',
    'contact.topicPlaceholder': 'Selecteer een onderwerp',
    'contact.topicSales': 'Sales',
    'contact.topicSupport': 'Technische Support',
    'contact.topicBilling': 'Facturatie',
    'contact.topicPartnership': 'Samenwerking',
    'contact.topicOther': 'Overig',
    'contact.subject': 'Onderwerp *',
    'contact.subjectPlaceholder': 'Hoe kunnen wij u helpen?',
    'contact.message': 'Bericht *',
    'contact.messagePlaceholder': 'Vertel ons meer over uw vraag of probleem...',
    'contact.send': 'Bericht Versturen',
    'contact.success': 'Bedankt voor uw bericht! Wij nemen binnen 24 uur contact met u op.',
    'contact.responseTime': 'Reactietijd',
    'contact.responseTimeDesc': 'Wij reageren doorgaans binnen',
    'contact.responseTimeHighlight': '24 uur',
    'contact.responseTimeSuffix': 'op werkdagen.',
    'contact.businessHours': 'Maandag - Vrijdag, 9:00 - 18:00 CET',
    'contact.location': 'Locatie',
    'contact.locationDesc': '🇪🇺 Gevestigd in de Europese Unie',
    
    // Transfers Panel
    'transfers.title': 'Recente Transfers',
    'transfers.search': 'Zoeken...',
    'transfers.noTransfers': 'Nog geen transfers',
    'transfers.noTransfersDesc': 'Verstuur uw eerste beveiligde document om te beginnen',
    'transfers.col.fileRecipient': 'Bestand & Ontvanger',
    'transfers.col.reference': 'Referentie',
    'transfers.col.evidence': 'Bewijskracht',
    'transfers.col.status': 'Status',
    'transfers.col.actions': 'Beheer',
    'transfers.btn.clone': 'Klonen',
    'transfers.btn.revoke': 'Intrekken',
    'transfers.btn.certificate': 'Certificaat',
    'transfers.revokeTitle': 'Toegang Intrekken',
    'transfers.revokeConfirm': 'Weet u zeker dat u de toegang tot deze transfer wilt intrekken? De ontvanger kan de bestanden niet meer downloaden.',
    'transfers.revokeCancel': 'Annuleren',
    'transfers.revokeAction': 'Toegang Intrekken',
    'transfers.linkCopied': 'Link gekopieerd naar klembord',
    'transfers.certificateStarted': 'Certificaat download gestart',
    'transfers.revokeSuccess': 'Toegang succesvol ingetrokken',
    'transfers.revokeFailed': 'Kon toegang niet intrekken',
    'transfers.reshareSuccess': 'Document succesvol opnieuw gedeeld',
    'transfers.reshareFailed': 'Kon document niet opnieuw delen',
    
    // Portals Panel
    'portals.title': 'Upload Portalen',
    'portals.subtitle': 'Maak gepersonaliseerde uploadlinks voor uw klanten',
    'portals.newPortal': 'Nieuw Portaal',
    'portals.newPortalTitle': 'Nieuw Upload Portaal',
    'portals.newPortalDesc': 'Maak een beveiligde uploadlink om te delen met uw klant.',
    'portals.name': 'Naam *',
    'portals.namePlaceholder': 'bijv. Belastingdocumenten - Jan Jansen',
    'portals.description': 'Beschrijving (optioneel)',
    'portals.descPlaceholder': 'Instructies voor uw klant...',
    'portals.expiryDate': 'Vervaldatum (optioneel)',
    'portals.idVerification': 'ID Verificatie',
    'portals.idVerifyDesc': 'Klanten moeten hun identiteit verifiëren met biometrisch ID voordat ze kunnen uploaden (juridisch bindend).',
    'portals.idVerifyUpgradeDesc': 'Vereis biometrische identiteitsverificatie voordat klanten documenten kunnen uploaden.',
    'portals.activeImmediately': 'Direct actief',
    'portals.active': 'Actief',
    'portals.inactive': 'Inactief',
    'portals.cancel': 'Annuleren',
    'portals.createPortal': 'Portaal Aanmaken',
    'portals.encrypted': 'End-to-end Versleuteld',
    'portals.encryptedDesc': 'Alle uploads via uw portalen zijn beveiligd met end-to-end versleuteling en verschijnen automatisch in uw dashboard met uw eigen huisstijl.',
    'portals.noPortals': 'Nog geen upload portalen',
    'portals.noPortalsDesc': 'Maak een portaal zodat klanten veilig documenten kunnen uploaden.',
    'portals.createFirst': 'Eerste Portaal Aanmaken',
    'portals.copyLink': 'Link',
    'portals.submissions': 'Inzendingen',
    'portals.viewPortal': 'Portaal Bekijken',
    'portals.edit': 'Bewerken',
    'portals.delete': 'Verwijderen',
    'portals.editTitle': 'Portaal Bewerken',
    'portals.saveChanges': 'Wijzigingen Opslaan',
    'portals.created': 'Aangemaakt',
    'portals.expires': 'Verloopt',
    'portals.upgrade': 'Upgraden',
    'portals.linkCopied': 'Link gekopieerd!',
    'portals.portalCreated': 'Upload portaal aangemaakt!',
    'portals.portalUpdated': 'Portaal bijgewerkt!',
    'portals.portalDeleted': 'Portaal verwijderd',
    'portals.loadFailed': 'Kon portalen niet laden',
    'portals.createFailed': 'Kon portaal niet aanmaken',
    'portals.updateFailed': 'Kon portaal niet bijwerken',
    'portals.deleteFailed': 'Kon portaal niet verwijderen',
    'portals.deleteConfirm': 'Weet u zeker dat u wilt verwijderen',
    'portals.nameRequired': 'Voer een naam in',
    'portals.phoneRequired': 'Telefoonnummer is vereist voor SMS-verificatie',
    'portals.submissionsTitle': 'Inzendingen',
    'portals.submissionsDesc': 'Bekijk alle documenten die via dit portaal zijn ingediend.',
    'portals.noSubmissions': 'Nog geen inzendingen',
    'portals.expired': 'Verlopen',
    'portals.files': 'bestanden',
    'portals.file': 'bestand',
    
    // Certificates Panel
    'certificates.title': 'Afleveringscertificaten',
    'certificates.description': 'Download juridisch bewijs van aflevering voor elke succesvolle download. Deze certificaten bevatten tijdstempel, IP-adres en ontvangstverificatie.',
    'certificates.noCertificates': 'Nog geen certificaten',
    'certificates.noCertificatesDesc': 'Certificaten worden gegenereerd wanneer ontvangers uw documenten downloaden',
    'certificates.deliveredTo': 'Succesvol afgeleverd aan',
    'certificates.download': 'Certificaat',
    'certificates.downloaded': 'Certificaat gedownload',
    
    // Security Panel
    'security.title': 'Beveiligingsinstellingen',
    'security.senderVerification': 'Identiteitsverificatie verzender',
    'security.twoFactor': 'Tweefactorauthenticatie',
    'security.changePassword': 'Wachtwoord wijzigen',
    'security.changePasswordDesc': 'Werk uw wachtwoord bij om uw account veilig te houden. Wij raden aan een sterk, uniek wachtwoord te gebruiken.',
    'security.newPassword': 'Nieuw wachtwoord',
    'security.newPasswordPlaceholder': 'Voer nieuw wachtwoord in',
    'security.minChars': 'Minimaal 8 tekens',
    'security.confirmPassword': 'Bevestig nieuw wachtwoord',
    'security.confirmPasswordPlaceholder': 'Bevestig nieuw wachtwoord',
    'security.changingPassword': 'Wijzigen...',
    'security.changePasswordBtn': 'Wachtwoord wijzigen',
    'security.passwordChanged': 'Wachtwoord succesvol gewijzigd',
    'security.passwordsRequired': 'Vul alle wachtwoordvelden in',
    'security.passwordTooShort': 'Wachtwoord moet minimaal 8 tekens bevatten',
    'security.passwordsMismatch': 'Wachtwoorden komen niet overeen',
    'security.passwordFailed': 'Kon wachtwoord niet wijzigen',
    'security.loginHistory': 'Inloggeschiedenis',
    'security.loginHistoryDesc': 'Recente aanmeldactiviteit voor uw account.',
    'security.loginHistorySoon': 'Inloggeschiedenis is binnenkort beschikbaar.',
    'security.loginHistorySoonDesc': 'We werken aan het bijhouden van inlogactiviteit voor uw veiligheid.',
    'security.unknownDevice': 'Onbekend apparaat',
    'security.unknownIP': 'Onbekend IP',
    
    // MFA Settings
    'mfa.title': 'Tweefactorauthenticatie',
    'mfa.enabledDesc': 'Uw account is beveiligd met een authenticator-app.',
    'mfa.disabledDesc': 'Voeg een extra beveiligingslaag toe aan uw account door een code van uw authenticator-app te vereisen bij het inloggen.',
    'mfa.disable': '2FA uitschakelen',
    'mfa.enable': '2FA inschakelen',
    'mfa.disableTitle': 'Tweefactorauthenticatie uitschakelen?',
    'mfa.disableDesc': 'Dit verwijdert de extra beveiligingslaag van uw account. U kunt het op elk moment opnieuw inschakelen.',
    'mfa.cancel': 'Annuleren',
    'mfa.disabling': 'Uitschakelen...',
    'mfa.enableTitle': 'Tweefactorauthenticatie inschakelen',
    'mfa.enableDesc': 'Stel een authenticator-app in om uw account te beveiligen',
    'mfa.enabled': 'Tweefactorauthenticatie ingeschakeld!',
    'mfa.disabled': 'Tweefactorauthenticatie uitgeschakeld',
    'mfa.disableFailed': 'Kon 2FA niet uitschakelen',
    
    // Profile Panel
    'profile.title': 'Mijn Profiel',
    'profile.save': 'Opslaan',
    'profile.saving': 'Opslaan...',
    'profile.changePhoto': 'Foto wijzigen',
    'profile.uploadPhoto': 'Foto uploaden',
    'profile.removePhoto': 'Verwijderen',
    'profile.personalInfo': 'Persoonlijke gegevens',
    'profile.firstName': 'Voornaam',
    'profile.lastName': 'Achternaam',
    'profile.companyInfo': 'Bedrijfsgegevens',
    'profile.companyName': 'Bedrijfsnaam',
    'profile.phone': 'Telefoon',
    'profile.addressInfo': 'Adresgegevens',
    'profile.address': 'Adres',
    'profile.postalCode': 'Postcode',
    'profile.city': 'Plaats',
    'profile.country': 'Land',
    'profile.loading': 'Laden...',
    'profile.notFound': 'Profiel niet gevonden',
    'profile.loadError': 'Fout bij laden profiel',
    'profile.saveError': 'Fout bij opslaan',
    'profile.saved': 'Profiel opgeslagen',
    'profile.photoUpdated': 'Profielfoto bijgewerkt!',
    'profile.photoRemoved': 'Profielfoto verwijderd',
    'profile.photoUploadFailed': 'Kon foto niet uploaden',
    'profile.photoRemoveFailed': 'Kon foto niet verwijderen',
    'profile.invalidFileType': 'Upload een JPG, PNG, WebP of GIF afbeelding',
    'profile.fileTooLarge': 'Afbeelding moet kleiner zijn dan 5MB',
    
    // Contacts Panel
    'contacts.title': 'Contacten',
    'contacts.newGroup': 'Nieuwe groep',
    'contacts.addContact': 'Contact toevoegen',
    'contacts.noContacts': 'Nog geen contacten',
    'contacts.noContactsDesc': 'Voeg contacten toe om snel bestanden te delen',
    'contacts.otherContacts': 'Overige contacten',
    'contacts.noContactsInGroup': 'Geen contacten in deze groep',
    'contacts.deleteGroupConfirm': 'Weet u zeker dat u deze groep wilt verwijderen?',
    'contacts.groupDeleted': 'Groep verwijderd',
    'contacts.contactDeleted': 'Contact verwijderd',
    'contacts.deleteError': 'Fout bij verwijderen',
    'contacts.newGroupTitle': 'Nieuwe groep',
    'contacts.groupName': 'Groepsnaam',
    'contacts.groupNamePlaceholder': 'bijv. Collega\'s',
    'contacts.groupDescription': 'Beschrijving (optioneel)',
    'contacts.groupDescPlaceholder': 'Korte beschrijving',
    'contacts.cancel': 'Annuleren',
    'contacts.create': 'Aanmaken',
    'contacts.groupCreated': 'Groep aangemaakt',
    'contacts.groupCreateError': 'Fout bij aanmaken groep',
    'contacts.addContactTitle': 'Contact toevoegen',
    'contacts.email': 'E-mail *',
    'contacts.emailPlaceholder': 'email@voorbeeld.nl',
    'contacts.name': 'Naam (optioneel)',
    'contacts.namePlaceholder': 'Jan Jansen',
    'contacts.add': 'Toevoegen',
    'contacts.contactAdded': 'Contact toegevoegd',
    'contacts.contactAddError': 'Fout bij toevoegen contact',
    'contacts.contactsLoadError': 'Fout bij laden contacten',
    'contacts.groupsLoadError': 'Fout bij laden groepen',
    'contacts.delete': 'Verwijderen',
  },
};
interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  // ✅ Safe default for SSR
  const [language, setLanguageState] = useState<Language>('en');

  // ✅ Run ONLY on client
  useEffect(() => {
    if (typeof window === 'undefined') return;

    const saved = localStorage.getItem('language');
    if (saved === 'en' || saved === 'nl') {
      setLanguageState(saved);
      return;
    }

    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('nl')) {
      setLanguageState('nl');
    }
  }, []);

  // Persist language
  useEffect(() => {
    if (typeof window === 'undefined') return;

    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, fallback?: string): string => {
    return translations[language][key] || fallback || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export { translations };